import { z } from 'zod';

/**
 * AI risk assessment result returned by the /ai/assess endpoint.
 */
export const riskAssessmentSchema = z.object({
  dealId: z.string().uuid(),
  riskScore: z.number().min(0).max(100),
  riskLevel: z.enum(['low', 'medium', 'high', 'critical']),
  flags: z.array(z.string()),
  recommendation: z.string(),
  analyzedAt: z.string().datetime(),
});

export type RiskAssessment = z.infer<typeof riskAssessmentSchema>;

/**
 * AI moderation action taken during a deal session.
 */
export const moderationActionSchema = z.object({
  id: z.string().uuid(),
  dealId: z.string().uuid(),
  sessionId: z.string().uuid(),
  action: z.enum(['warn', 'flag', 'pause', 'escalate']),
  reason: z.string(),
  timestamp: z.string().datetime(),
});

export type ModerationAction = z.infer<typeof moderationActionSchema>;

/**
 * AI conversation message within a deal session.
 */
export const aiMessageSchema = z.object({
  id: z.string().uuid(),
  dealId: z.string().uuid(),
  sessionId: z.string().uuid(),
  role: z.enum(['user', 'assistant', 'system']),
  content: z.string(),
  metadata: z.record(z.unknown()).optional(),
  createdAt: z.string().datetime(),
});

export type AiMessage = z.infer<typeof aiMessageSchema>;

/**
 * Escrow instruction generated by AI for Solana program execution.
 */
export const escrowInstructionSchema = z.object({
  dealId: z.string().uuid(),
  action: z.enum(['create', 'release', 'refund', 'dispute']),
  amount: z.number().positive(),
  sellerWallet: z.string().min(32),
  buyerWallet: z.string().min(32),
  conditions: z.array(z.string()).optional(),
});

export type EscrowInstruction = z.infer<typeof escrowInstructionSchema>;