import { z } from 'zod';

/**
 * Dispute status lifecycle.
 * Opened → Investigation → Resolved (buyer_win / seller_win / split).
 */
export const disputeStatusSchema = z.enum([
  'opened',
  'investigation',
  'buyer_win',
  'seller_win',
  'split',
]);
export type DisputeStatus = z.infer<typeof disputeStatusSchema>;

/**
 * Dispute resolution reason taxonomy.
 */
export const disputeReasonSchema = z.enum([
  'delivery_not_as_described',
  'payment_not_received',
  'service_not_completed',
  'buyer_no_show',
  'seller_no_show',
  'terms_violation',
  'other',
]);
export type DisputeReason = z.infer<typeof disputeReasonSchema>;

/**
 * Dispute report generated by AI Dispute Resolver.
 */
export const disputeReportSchema = z.object({
  id: z.string(),
  dealId: z.string(),
  openedBy: z.string(), // wallet address of the disputant
  reason: disputeReasonSchema,
  description: z.string(),
  status: disputeStatusSchema.default('opened'),
  transcriptSummary: z.string(),
  riskEventsSummary: z.string(),
  evidenceHashes: z.array(z.string()).default([]),
  aiRecommendation: z.string(),
  resolutionNote: z.string().nullable(),
  resolvedBy: z.string().nullable(),
  resolvedAt: z.string().datetime().nullable(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type DisputeReport = z.infer<typeof disputeReportSchema>;

// ──────────────────────────────────────────────
// DB-compatible enums + request payloads (API surface)
//
// These match the Prisma `DisputeStatus` / `DisputeResolution` enums so the API
// can validate against DB-compatible values. Added alongside the existing
// lowercase schemas above (which other code may still consume) — not a replacement.
// ──────────────────────────────────────────────

/** Dispute status — matches Prisma `DisputeStatus`. */
export const disputeStatusDbSchema = z.enum([
  'Open',
  'UnderReview',
  'Resolved',
  'Escalated',
]);
export type DisputeStatusDb = z.infer<typeof disputeStatusDbSchema>;

/** Dispute resolution outcome — matches Prisma `DisputeResolution`. */
export const disputeResolutionSchema = z.enum([
  'ReleaseToSeller',
  'RefundToBuyer',
  'SplitPayment',
]);
export type DisputeResolution = z.infer<typeof disputeResolutionSchema>;

/** Request to open a dispute on a deal. */
export const createDisputeRequestSchema = z.object({
  dealId: z.string(),
  raisedBy: z.string(),
  reason: disputeReasonSchema,
  description: z.string().min(1),
});
export type CreateDisputeRequest = z.infer<typeof createDisputeRequestSchema>;

/** Request to resolve a dispute with a DB-compatible resolution outcome. */
export const resolveDisputeRequestSchema = z.object({
  resolution: disputeResolutionSchema,
  resolvedBy: z.string(),
  resolutionNote: z.string().optional(),
});
export type ResolveDisputeRequest = z.infer<typeof resolveDisputeRequestSchema>;