import {
  SCAM_INTENT_SUGGESTED_ACTION,
  type DealStatus,
  type RiskLevel,
  type ScamIntent,
} from '@trustroom/types';

/**
 * A deterministic Scam Guard rule. Rules are the fast first layer of detection
 * (run before the LLM intent classifier). Each rule contributes a score delta;
 * the aggregator combines deltas into a final risk level.
 *
 * Matching is two-pronged:
 *  - `keywords`: substring match against normalized (lowercased, accent-folded) text.
 *  - `patterns`: regex match against the normalized text. Patterns capture the
 *    "vòng vo" / paraphrased phrasings that a flat keyword list misses
 *    (e.g. "cứ bấm hoàn tất đi rồi mình gửi sau").
 */
export interface ScamRule {
  ruleId: string;
  intent: ScamIntent;
  riskLevel: RiskLevel;
  /** Base score contribution (0-100). */
  score: number;
  /** Lowercased keyword/phrase triggers (matched against normalized text). VI + EN. */
  keywords?: string[];
  /** Regex triggers against normalized text — covers paraphrased / indirect phrasing. */
  patterns?: RegExp[];
  /** If set, the rule only fires when the deal is NOT in one of these states. */
  invalidBeforeStates?: DealStatus[];
  /**
   * True when this intent directly threatens escrowed funds. Used by the
   * aggregator to decide whether to recommend locking the Release button.
   */
  escrowThreat?: boolean;
  /**
   * True when repeating this behavior should accrue the repetition penalty
   * (technical brief §6.1 "lặp lại cùng hành vi nguy hiểm").
   */
  repeatable?: boolean;
  /** Human-readable explanation shown to the user (must explain the reason). */
  message: string;
}

/**
 * Returns the canonical user-facing action for an intent. Falls back to a generic
 * caution string for intents without a dedicated entry.
 */
export function suggestedActionFor(intent: ScamIntent): string {
  return (
    SCAM_INTENT_SUGGESTED_ACTION[intent] ??
    'Review the deal terms carefully before taking any action.'
  );
}

/**
 * MVP rule catalog. Keywords + regex intentionally include Vietnamese phrasings
 * because transcripts are VI / EN / mixed. Normalization (see `detect.ts`) folds
 * Vietnamese diacritics, so the patterns here are written without accents and a
 * single rule matches both "release trước" and "release truoc".
 *
 * This is the deterministic layer; the LLM intent classifier + embedding playbook
 * extend it with semantic coverage for paraphrases not enumerated here.
 */
export const SCAM_RULES: ScamRule[] = [
  {
    ruleId: 'EARLY_RELEASE',
    intent: 'early_release_request',
    riskLevel: 'high',
    score: 40,
    keywords: [
      'release first',
      'release truoc',
      'confirm first',
      'complete first',
      'send later',
      'gui file sau',
      'gui hang sau',
      'chuyen truoc',
      'tin tui di',
      'trust me',
    ],
    patterns: [
      // "release/confirm/complete/bấm hoàn tất ... (rồi/then) ... gửi/giao/chuyển sau"
      /\b(release|confirm|complete|hoan tat|xac nhan|bam)\b.{0,40}\b(truoc|first|di)\b/,
      /\b(truoc|first)\b.{0,30}\b(gui|giao|chuyen|send|deliver)\b.{0,20}\b(sau|later)\b/,
      /\bcu (release|hoan tat|xac nhan|bam)\b/,
    ],
    invalidBeforeStates: ['DeliverySubmitted', 'ReadyToRelease'],
    escrowThreat: true,
    repeatable: true,
    message: 'Counterparty is asking to release escrow before delivery is verified.',
  },
  {
    ruleId: 'OFF_PLATFORM',
    intent: 'move_off_platform',
    riskLevel: 'high',
    score: 35,
    keywords: [
      'telegram',
      'zalo',
      'whatsapp',
      'messenger',
      'discord',
      'wechat',
      'viber',
      'app khac',
      'nen tang khac',
      'platform khac',
      'qua ben ngoai',
      'giao dich ngoai',
      'noi chuyen ngoai',
      'noi chuyen rieng',
      'ra ngoai noi',
      'khong chat o day',
      'khong nhan o day',
      'khong can o room nay',
      'bo escrow',
      'ne escrow',
      'direct wallet',
      'nhan rieng',
      'inbox',
      'private chat',
      'off platform',
    ],
    patterns: [
      /\b(qua|sang|chuyen sang|ra)\b.{0,15}\b(telegram|zalo|whatsapp|messenger|discord|ngoai)\b/,
      /\bnoi chuyen\b.{0,15}\b(rieng|ngoai|cho tien|cho nhanh)\b/,
      /\bkhong (can|thich)\b.{0,10}\b(escrow|ai|nghe|giam sat)\b/,
      /\b(chuyen|doi|qua)\b.{0,15}\b(app|nen tang|platform)\b.{0,10}\b(khac|ngoai)\b/,
      /\b(dung|khong)\b.{0,12}\b(chat|nhan tin)\b.{0,12}\b(o day|trong room|tren he thong)\b/,
      /\b(giao dich|noi)\b.{0,12}\b(ngoai|rieng)\b.{0,12}\b(room|nen tang|he thong)?\b/,
      /\b(bo|ne|khong can)\b.{0,10}\b(escrow)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'Counterparty is trying to move the deal off-platform, where you lose protection.',
  },
  {
    ruleId: 'CREDENTIAL_REQUEST',
    intent: 'credential_request',
    riskLevel: 'critical',
    score: 100,
    keywords: [
      'seed phrase',
      'seedphrase',
      'private key',
      'recovery phrase',
      'cum tu khoi phuc',
      'mat khau',
      'password',
      'otp',
      'ma xac minh',
      'ma otp',
      'anydesk',
      'teamviewer',
      'remote access',
    ],
    patterns: [
      /\b(gui|cho|xin|nhap|share)\b.{0,20}\b(seed|private key|recovery|otp|mat khau|password)\b/,
      /\b(cai|install)\b.{0,15}\b(app|ung dung)\b.{0,20}\b(ket noi vi|connect wallet)\b/,
    ],
    escrowThreat: true,
    message: 'Never share your seed phrase, private key, OTP, or password with anyone.',
  },
  {
    ruleId: 'EXTERNAL_WALLET',
    intent: 'external_wallet',
    riskLevel: 'critical',
    score: 80,
    // No keyword/pattern triggers: this rule is fired by the wallet-address parser
    // (see wallet-parser.ts) when an on-chain address that is NOT part of the
    // verified deal/escrow appears in the transcript.
    escrowThreat: true,
    repeatable: true,
    message: 'A wallet address that is not part of the verified deal/escrow was detected.',
  },
  {
    ruleId: 'SPLIT_PAYMENT',
    intent: 'split_payment',
    riskLevel: 'high',
    score: 35,
    keywords: [
      'chia ra',
      'tach ra',
      'mot phan ngoai escrow',
      'coc truoc',
      'dat coc truoc',
      'gui truoc 30',
      'gui truoc mot phan',
      'split payment',
      'partial payment',
      'escrow chi de',
    ],
    patterns: [
      /\b(gui|chuyen|coc)\b.{0,15}\b(truoc)\b.{0,15}\b(\d{1,3} ?%|mot phan|ngoai escrow)\b/,
      /\bchia\b.{0,10}\b(\d|nhieu)\b.{0,10}\b(vi|lan|phan)\b/,
      /\bescrow chi (de|la)\b.{0,15}\b(tuong trung|hinh thuc)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'Counterparty wants to split the payment or pay partly outside escrow — only the full escrow deposit is protected.',
  },
  {
    ruleId: 'FAKE_PAYMENT_PROOF',
    intent: 'fake_payment_proof',
    riskLevel: 'high',
    score: 40,
    keywords: [
      'da gui bill',
      'anh chuyen khoan',
      'anh bill',
      'bien lai',
      'screenshot',
      'screen shot',
      'i already paid',
      'da thanh toan roi',
      'da chuyen roi',
      'tien chac chan ve',
      'ngan hang bao pending',
    ],
    patterns: [
      /\b(da|toi|minh)\b.{0,10}\b(chuyen|thanh toan|paid|gui tien)\b.{0,25}\b(release|hoan tat|giao|gui hang|con cho gi)\b/,
      /\b(xem|day|gui)\b.{0,10}\b(anh|bill|bien lai|email|sms)\b.{0,20}\b(release|di|roi)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'A screenshot is not proof of an on-chain payment. Verify the transaction before releasing.',
  },
  {
    ruleId: 'TIME_PRESSURE',
    intent: 'time_pressure',
    riskLevel: 'medium',
    score: 20,
    keywords: [
      'nhanh len',
      'gap',
      'khan',
      'last chance',
      'co hoi cuoi',
      'het han',
      'chi con',
      'het gio',
      'lam ngay',
      'ngay bay gio',
      'right now',
      'hurry',
      'limited time',
    ],
    patterns: [
      /\bchi con\b.{0,10}\b(\d+\s*(phut|giay|gio|minute|second)|it)\b/,
      /\bneu (ban )?khong\b.{0,20}\b(report|mat deal|mat co hoi|huy)\b/,
    ],
    repeatable: true,
    message: 'Be cautious of urgency/time pressure — it is a common manipulation tactic.',
  },
  {
    ruleId: 'IMPERSONATION',
    intent: 'impersonation',
    riskLevel: 'high',
    score: 35,
    keywords: [
      'i am support',
      'toi la admin',
      'toi la support',
      'minh la admin',
      'nhan vien',
      'arbitrator',
      'trong tai',
      'dai dien du an',
      'official support',
      'he thong bao tri',
    ],
    patterns: [
      /\b(toi|minh|i)\b.{0,5}\b(la|am)\b.{0,10}\b(support|admin|nhan vien|trong tai|moderator)\b/,
      /\badmin (bao|noi|yeu cau)\b.{0,15}\b(release|chuyen|gui)\b/,
    ],
    repeatable: true,
    message: 'This identity is not a verified TrustRoom support/admin/arbitrator.',
  },
  {
    ruleId: 'TERM_CHANGE_AFTER_DEPOSIT',
    intent: 'term_change_after_deposit',
    riskLevel: 'high',
    score: 25,
    keywords: [
      'gio gia phai',
      'tra them',
      'doi gia',
      'phai release mot phan',
      'lui deadline',
      'doi deadline',
      'muon ban full',
      'them phi',
    ],
    patterns: [
      /\b(gio|bay gio)\b.{0,15}\b(gia|deadline|phai)\b.{0,15}\b(la|phai|them)\b/,
      /\b(deadline|gia)\b.{0,10}\b(phai )?(lui|doi|tang|len)\b/,
    ],
    // Only meaningful once the deal terms are locked / funds deposited.
    invalidBeforeStates: ['Draft', 'Created', 'WaitingForCounterparty', 'WalletVerified'],
    repeatable: true,
    message: 'Counterparty is changing agreed terms after deposit. Both parties must sign an amendment.',
  },
  {
    ruleId: 'AMBIGUOUS_TERMS',
    intent: 'ambiguous_terms',
    riskLevel: 'medium',
    score: 15,
    keywords: [
      'cu tin toi',
      'khong can ghi',
      'khong can xac nhan',
      'noi mieng',
      'cu deposit di roi ban',
      'dung ghi cai nay',
      'noi vay thoi',
    ],
    patterns: [
      /\b(khong can|dung)\b.{0,10}\b(ghi|xac nhan|ky)\b/,
      /\bcu (tin|deposit|chuyen)\b.{0,15}\b(di|roi)\b.{0,10}\b(ban tiep|noi sau)?\b/,
    ],
    repeatable: true,
    message: 'Counterparty is avoiding clear written terms. Confirm asset, price, deadline, and release condition first.',
  },
  {
    ruleId: 'UNVERIFIED_DELIVERY',
    intent: 'unverified_delivery',
    riskLevel: 'medium',
    score: 20,
    keywords: [
      'toi gui roi ma',
      'da lam xong',
      'nft dang pending',
      'chua upload duoc',
      'dung hoi them',
      'file o link nay',
    ],
    patterns: [
      /\b(da|toi)\b.{0,5}\b(gui|giao|lam xong)\b.{0,10}\b(roi)\b.{0,15}\b(ma|release|di)?\b/,
      /\b(nft|token|hang)\b.{0,10}\b(dang pending|chua xong|chua co)\b.{0,15}\b(release|di)\b/,
    ],
    invalidBeforeStates: ['ReadyToRelease', 'Released'],
    escrowThreat: true,
    repeatable: true,
    message: 'Delivery is claimed but not verified. Require valid delivery proof before releasing.',
  },
  {
    ruleId: 'PHISHING_LINK',
    intent: 'phishing_link',
    riskLevel: 'high',
    score: 35,
    // Fired by the URL parser in wallet-parser.ts when a suspicious link/domain
    // (shortener, look-alike, or "connect wallet / claim" lure) is detected. The
    // keywords below catch the common social-engineering lures around such links.
    keywords: [
      'ket noi vi',
      'connect wallet',
      'claim airdrop',
      'nhan thuong',
      'verify wallet',
      'xac minh vi',
      'ky thu transaction',
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'A suspicious link or wallet-connect lure was detected. Do not open it or sign anything.',
  },

  // ────────────────────────────────────────────────────────────────
  // Mission C: Stronger scam rules
  // ────────────────────────────────────────────────────────────────

  {
    ruleId: 'GUARANTEED_PROFIT',
    intent: 'guaranteed_profit',
    riskLevel: 'high',
    score: 35,
    keywords: [
      'dam bao loi',
      'loi nhuan dam bao',
      'chac chan loi',
      'khong bao ho',
      'guaranteed profit',
      'guaranteed return',
      'sure profit',
      '100% profit',
      'loi to',
      'nhanh giau',
      'lam giau',
      'investment return',
      'daily income',
      'thu nhap ngay',
      'loi suat cao',
      'high yield',
      'risk free investment',
      'risk-free investment',
      'double your money',
      'nhan doi tien',
      'passive income',
      'thu pass dong',
      'guaranteed income',
    ],
    patterns: [
      /\b(dam bao|chac chan|bao dam|khong bao ho)\b.{0,20}\b(loi|return|profit|income|thu nhap)\b/,
      /\b(\d{2,3}\s?%).{0,15}\b(profit|return|interest|loi|thu nhap|tuan|thang|daily|weekly)\b/,
      /\b(chac chan|dam bao|chac chan)\b.{0,15}\b(nhan duoc|kiem duoc|co duoc|get)\b/,
      /\b(risk.{0,5}free)\b.{0,15}\b(investment|return|profit|income)\b/,
      /\b(double|nhan doi)\b.{0,10}\b(your|tien|money|dong)\b/,
      /\b(passive income|thu nhap pass)\b.{0,10}\b(guaranteed|dam bao|bao dam)\b/,
      /\b(guaranteed|dam bao)\b.{0,10}\b(passive income|thu nhap)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'Promises of guaranteed profit or high fixed returns are a hallmark of investment scams. No legitimate deal guarantees returns.',
  },
  {
    ruleId: 'FAKE_INVESTMENT_APP',
    intent: 'fake_investment_app',
    riskLevel: 'critical',
    score: 70,
    keywords: [
      'cai app dau tu',
      'install investment app',
      'download app',
      'download investment app',
      'ung dung dau tu',
      'trading app',
      'crypto investment',
      'mo tai khoan dau tu',
      'open investment account',
      'connect bank account',
      'link bank account',
      'ket noi tai khoan ngan hang',
      'gui tien vao app',
      'deposit into app',
      'app nay loi lam',
      'this app pays',
      'platform link',
      'dang ky tai khoan',
      'register account',
      'platform to trade',
      'use this platform',
    ],
    patterns: [
      /\b(cai|install|download|tai)\b.{0,20}\b(app|ung dung)\b.{0,20}\b(dau tu|trading|crypto|investment)\b/,
      /\b(cai|install|download|tai)\b.{0,20}\b(investment|trading|crypto|dau tu)\b.{0,10}\b(app|ung dung)\b/,
      /\b(mo|tao|dang ky|open|create|register)\b.{0,15}\b(tai khoan|account)\b.{0,15}\b(dau tu|investment|trading)\b/,
      /\b(gui|chuyen|deposit)\b.{0,15}\b(tien|money|fund)\b.{0,15}\b(vao app|into app|vao tai khoan)\b/,
      /\b(platform|nen tang).{0,10}\b(link|dang ky|register|trade|giao dich)\b/,
      /\b(use|dung|su dung)\b.{0,10}\b(this|nay)\b.{0,10}\b(platform|nen tang)\b.{0,10}\b(to|de)\b.{0,10}\b(trade|giao dich|crypto)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'Counterparty is directing you to install a fake investment app or open an investment account. This is a common pig-butchering scam.',
  },
  {
    ruleId: 'RECOVERY_FEE',
    intent: 'recovery_fee',
    riskLevel: 'critical',
    score: 70,
    keywords: [
      'phi khoi phuc',
      'recovery fee',
      'phi tra lai',
      'unlock fee',
      'phi mo khoa',
      'send fee first',
      'gui phi truoc',
      'pay to recover',
      'phi giai phong',
      'release fee',
      'unfreeze fee',
      'phi xu ly',
      'phi xu ly truoc',
      'upfront fee',
      'processing fee',
      'phi dich vu',
      'service fee to',
    ],
    patterns: [
      /\b(gui|pay|chuyen|send)\b.{0,15}\b(phi|fee|tien)\b.{0,15}\b(khoi phuc|recover|unlock|mo khoa|giai phong|unfreeze|tra lai)\b/,
      /\b(phi|fee)\b.{0,10}\b(khoi phuc|recover|unlock|mo khoa|giai phong|xu ly|dich vu)\b/,
      /\b(phai|can|need|must)\b.{0,10}\b(pay|gui|chuyen)\b.{0,10}\b(phi|fee)\b.{0,10}\b(truoc|first|de|to)\b/,
      /\b(pay|dong|gui|chuyen|pay)\b.{0,10}\b(phi|xu ly|dich vu|fee|processing)\b/,
      /\b(upfront|tien truoc|gui truoc)\b.{0,10}\b(fee|phi)\b/,
      /\b(deposit|gui tien|nap tien)\b.{0,15}\b(first|truoc)\b.{0,15}\b(unlock|mo khoa|withdraw|rut)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'Requests for "recovery fees", "unlock fees", or "release fees" to get your money back are always scams. No legitimate platform charges these.',
  },
  {
    ruleId: 'SECRECY_PRESSURE',
    intent: 'secrecy_pressure',
    riskLevel: 'high',
    score: 30,
    keywords: [
      'khong ai duoc biet',
      'don tell anyone',
      'do not tell anyone',
      'keep secret',
      'keep this secret',
      'giu bi mat',
      'no one should know',
      'nguoi khong lien quan',
      'khong noi voi ai',
      'dung noi voi ai',
      'tui minh thoi',
      'just between us',
      'noi rieng voi minh',
      'don report',
      'khong can bao cao',
      'khong can thong bao',
      'stays between us',
      'between us only',
      'trust me only',
      'chi minh thoi',
    ],
    patterns: [
      /\b(khong|don'?t|do not)\b.{0,10}\b(no|biet|tell|share|say|thong bao|bao cao)\b.{0,10}\b(ai|anyone|anybody|nguoi)\b/,
      /\b(giu|keep)\b.{0,15}\b(bi mat|secret|private|this)\b/,
      /\b(chi (giua|between)|just between)\b.{0,10}\b(minh|us|tui)\b/,
      /\b(not)\b.{0,5}\b(a|one)\b.{0,10}\b(should know|biet|noi)\b/,
      /\b(stays?|remains?)\b.{0,10}\b(between|giua)\b.{0,10}\b(us|minh|tui)\b/,
      /\b(trust)\b.{0,5}\b(me|toi)\b.{0,10}\b(only|thoi|chi)\b/,
      /\b(dung|don'?t|do not)\b.{0,10}\b involve \b/,
    ],
    repeatable: true,
    message: 'Counterparty is pressuring you to keep the deal secret. Legitimate deals do not require secrecy from others.',
  },
  {
    ruleId: 'EMERGENCY_MONEY',
    intent: 'emergency_money_request',
    riskLevel: 'high',
    score: 35,
    keywords: [
      'gap tien',
      'can tien ngay',
      'urgent money',
      'emergency',
      'emergency money',
      'cap tien',
      'toi dang bi',
      'i am in trouble',
      'help me',
      'giup toi',
      'muon tien gap',
      'need money urgently',
      'need funds urgently',
      'need funds immediately',
      'bi mat tien',
      'lost money',
      'cuu toi',
      'save me',
      'life or death',
      'mat mang',
      'critical situation',
      'tinh huong gap',
      'need funds',
      'can funds',
      'medical emergency',
      'cap cuu',
    ],
    patterns: [
      /\b(can|need|muon|gap|cap)\b.{0,10}\b(tien|money|fund|funds|ngay|now|urgently|gap)\b/,
      /\b(dang|am|in)\b.{0,10}\b(trouble|bi|in trouble|danger)\b/,
      /\b(help|giup|cuu)\b.{0,10}\b(me|toi)\b.{0,10}\b(tien|money)\b/,
      /\b(critical|nghiem trong|gap doc)\b.{0,10}\b(situation|tinh huong|truong hop)\b/,
      /\b(need|can|muon)\b.{0,10}\b(funds|tien)\b.{0,10}\b(immediately|ngay|gap|urgently)\b/,
    ],
    repeatable: true,
    message: 'Counterparty is making emotional emergency money requests to pressure you. Take time to verify claims before releasing any funds.',
  },
  {
    ruleId: 'GIFT_CARD_WIRE',
    intent: 'gift_card_wire_transfer',
    riskLevel: 'critical',
    score: 65,
    keywords: [
      'gift card',
      'the cao',
      'the nap',
      'the tien',
      'itunes card',
      'google play card',
      'amazon card',
      'wire transfer',
      'chuyen khoan ngan hang',
      'bank transfer',
      'western union',
      'moneygram',
      'prepaid card',
      'the truoc tien',
      'tien mat',
      'cash',
      'zelle',
      'venmo',
      'cashapp',
      'paypal friends',
      'steam wallet',
      'the steam',
      'wallet code',
      'ma the cao',
      'scratch card',
      'card code',
    ],
    patterns: [
      /\b(buy|muon|mua)\b.{0,15}\b(gift card|the cao|the nap|itunes|google play|amazon)\b/,
      /\b(send|gui|chuyen)\b.{0,10}\b(wire|bank transfer|western union|moneygram)\b/,
      /\b(pay|thanh toan)\b.{0,10}\b(prepaid|prepaid card|the truoc|the tien)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'Gift cards, wire transfers, and prepaid cards are untraceable payment methods favored by scammers. Never use these for deals.',
  },
  {
    ruleId: 'REMOTE_ACCESS',
    intent: 'remote_access_request',
    riskLevel: 'critical',
    score: 75,
    keywords: [
      'anydesk',
      'teamviewer',
      'remote access',
      'remote desktop',
      'screen share',
      'chia man hinh',
      'truy cap may tinh',
      'control computer',
      'phan mem quan ly',
      'remote control',
      'connect my computer',
      'ket noi may tinh',
      'ultraview',
      'supremo',
      'rustdesk',
    ],
    patterns: [
      /\b(open|cai|install|download|install|mo)\b.{0,15}\b(anydesk|teamviewer|ultraview|supremo|rustdesk|remote)\b/,
      /\b(chia|share|stream)\b.{0,10}\b(man hinh|screen|desktop)\b/,
      /\b(remote|truy cap|control)\b.{0,10}\b(may tinh|computer|desktop|pc)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'Requests for remote access tools (AnyDesk, TeamViewer, etc.) allow the scammer to control your device and steal funds. Never install these.',
  },
  {
    ruleId: 'FAKE_SUPPORT',
    intent: 'fake_support_admin',
    riskLevel: 'high',
    score: 45,
    keywords: [
      'trustroom support',
      'trustroom admin',
      'platform support',
      'he thong ho tro',
      'admin ho tro',
      'support team',
      'customer service',
      'bo phan ho tro',
      'verification team',
      'doi ngu xac minh',
      'nhan vien xac minh',
      'authorized representative',
      'official verifier',
      'official representative',
      'quan tri vien',
      'admin vien',
      'moderator',
      'platform moderator',
    ],
    patterns: [
      /\b(toi|minh|we|i)\b.{0,5}\b(la|am|from)\b.{0,10}\b(support|admin|trustroom|platform|ho tro)\b/,
      /\b(toi|minh|we|i)\b.{0,5}\b(la|am|from)\b.{0,10}\b(verifier|representative|moderator|quan tri)\b/,
      /\b(support|admin)\b.{0,5}\b(no|bao|yeu cau|say|tell)\b.{0,15}\b(release|pay|gui|chuyen)\b/,
      /\b(verification|xac minh)\b.{0,10}\b(team|doi ngu|nhan vien)\b.{0,10}\b(yeu cau|require|ask)\b/,
      /\b(official|chinh thuc)\b.{0,10}\b(verifier| nguoi xac minh|representative)\b/,
    ],
    repeatable: true,
    message: 'This person is impersonating TrustRoom support or admin. TrustRoom staff will never ask you to release funds or share credentials through chat.',
  },
  {
    ruleId: 'QR_PAYMENT_LURE',
    intent: 'qr_payment_lure',
    riskLevel: 'high',
    score: 40,
    keywords: [
      'scan qr',
      'ma qr',
      'verify wallet',
      'xac minh vi',
      'wallet verification',
      'connect wallet',
      'ket noi vi',
      'link verify',
      'verify connection',
      'signature request',
      'ky giao dich',
      'sign transaction',
      'confirm wallet',
      'xac thuc vi',
      'qr payment',
      'thanhtoan qr',
    ],
    patterns: [
      /\b(quet|scan|open|mo)\b.{0,10}\b(qr|ma qr|qr code)\b/,
      /\b(verify|xac minh|xac thuc|connect|ket noi|confirm)\b.{0,10}\b(wallet|vi|signature|giao dich)\b/,
      /\b(send|gui|chia)\b.{0,10}\b(link|qr|ma)\b.{0,10}\b(verify|xac minh|xac thuc|wallet|vi)\b/,
      /\b(qr).{0,10}\b(code|ma)\b.{0,15}\b(verify|xac minh|xac thuc|wallet|vi|payment)\b/,
      /\b(confirm|verify|xac minh|xac thuc)\b.{0,10}\b(wallet|vi)\b.{0,10}\b(with|bang|fee|phi)\b/,
    ],
    escrowThreat: true,
    repeatable: true,
    message: 'QR codes and wallet verification links are common lures to steal your credentials or sign malicious transactions. Do not scan or click.',
  },
  {
    ruleId: 'STORY_INCONSISTENCY',
    intent: 'story_inconsistency',
    riskLevel: 'medium',
    score: 20,
    keywords: [
      'khong nhu da noi',
      'doi y',
      'doi mind',
      'thay doi',
      'actually no',
      'actually i was',
      'wait i meant',
      'toi nhom roi',
      'sai roi',
      'i was wrong',
      'i am wrong',
      'moi nhat la',
      'change of plan',
      'instead',
      'thay the',
      'dung wallet nay',
      'use this wallet',
      'send to this wallet',
      'different wallet',
      'wallet khac',
      'actually',
      'but actually',
    ],
    patterns: [
      /\b(khong|no|not)\b.{0,10}\b nhu \b.{0,10}\b(da noi|said|told)\b/,
      /\b(doi|thay doi|change)\b.{0,10}\b(y|plan|ke hoach|dea)\b/,
      /\b(toi|i)\b.{0,10}\b(sai|wrong|nhom|mistake)\b/,
      /\b(actually|thuc te|that la)\b/,
      /\b(but|nhung)\b.{0,5}\b(actually|thuc te)\b/,
      /\b(instead|thay the|gia)\b.{0,10}\b(wallet|vi)\b/,
      /\b(send|gui|chuyen)\b.{0,10}\b(to|den|vao)\b.{0,10}\b(this|nay|khac|instead)\b.{0,10}\b(wallet|vi)?\b/,
      /\b(different|khac|other)\b.{0,10}\b(wallet|vi)\b/,
    ],
    repeatable: true,
    message: 'Counterparty is changing their story or contradicting earlier statements. This may indicate deception — verify all claims independently.',
  },
];
